---
title: "Storm Data Analysis"
author: "Bastiaan Quast"
date: "Monday, June 16, 2014"
output: html_document
---

Synopsis
---


Data Processing
---

Download the data and import it.

```{r}
file.url <- 'https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2'
file.dest <- 'StormData.csv.bz2'
download.file(file.url, file.dest, method='auto')

library(R.utils, warn.conflicts=FALSE) # needs to be installed (using install.packages('R.utils') )
bunzip2(file.dest, remove=TRUE)
close(con)

StormData <- read.csv('StormData.csv')
```

Recode the names, save to an RData file and remove the **csv** file. Create a variable which sums up all damage variables to one count.

```{r}
names(StormData) <- tolower( names(StormData) )
names(StormData) <- gsub( '_$', '', names(StormData) )
names(StormData) <- gsub( '_$', '', names(StormData) ) # 2x
names(StormData) <- gsub( '_', '.', names(StormData) )
StormData$total.dmg <- sum(StormData$propdmg, StormData$cropdmg)
StormData$bgn.date <- gsub( ' 0:00:00$', '', StormData$bgn.date )
StormData$bgn.date <- as.Date(StormData$bgn.date, '%d/%m/%Y')
StormData$year <- format(StormData$bgn.date, '%Y')
save(StormData, file = 'StormData.RData')
file.remove('StormData.csv')
attach(StormData)
```

Summarise the fatalities, injuries and damage, once for totals and once for averages.

```{r}
library(dplyr, warn.conflicts=FALSE)
total.stat <- summarise( group_by(StormData, evtype), total.fatalities=sum(fatalities), total.injuries=sum(injuries), total.damage = sum(total.dmg) )
mean.stat <- summarise( group_by(StormData, evtype), mean.fatalities=mean(fatalities), mean.injuries=mean(injuries) )
top.events <- total.stat[with(total.stat, order(-total.fatalities, -total.injuries)),]$evtype[1:10]
top.stat <- subset(total.stat, evtype %in% top.events)
```


Results
---
Print the summary tables

```{r}
total.stat[with(total.stat, order(-total.fatalities, -total.injuries)),]
total.stat[with(total.stat, order(-total.damage)),]
mean.stat[with(mean.stat, order(-mean.fatalities, -mean.injuries)),]
```

```{r}
library(ggplot2)
plot <- ggplot(top.stat, aes(evtype, weight=total.fatalities ) )
plot <- plot + geom_bar()
plot

plot <- ggplot(top.stat, aes(evtype, weight=total.damage ) )
plot <- plot + geom_bar()
plot

# plot data
plot <- ggplot(StormData, aes(f, weight=fatalities) )
plot <- plot + geom_bar()
plot
```